---
- hosts: webservers
  become: yes
  tasks:
  
  - name: Install pip3
    apt:
      name: python3-pip
      state: present
      update_cache: no
  
  - name: Install flask
    pip:
      name: flask
      executable: pip3
  
  - name: Copy source
    copy:
      src: '{{ playbook_dir }}/source/'
      dest: /var/www/site/

  - name: Copy service
    copy:
      src: '{{ playbook_dir }}/site_flask.service'
      dest: /etc/systemd/system/

  - name: Enable service
    service: name=site_flask.service enabled=yes

  - name: Start supervisord
    service: name=site_flask.service state=started
  
  # - name: Shell
  #   shell: nohup python3 /home/antosha/site/test_site.py &
  #   args:
  #     chdir: /home/antosha/site/


