#!/bin/bash
yum update -y
yum install httpd -y
systemctl start httpd.service
systemctl enable httpd.service
aws s3 cp s3://mydoombucket777/index.html /var/www/html/
echo "$HOSTNAME" >> /var/www/html/index.html