#!/bin/bash
read -e -p "How many days older: " var_days  
read -e -p "How many hours older: " var_hours 
read -e -p "How many minutes older: " var_minutes
mass=("${var_days}" "${var_hours}" "${var_minutes}")


for i in "${!mass[@]}"; do
	if [[ "${mass[$i]}" =~ ^-?[0-9]+$ ]]; then	
		continue
	elif [[ -z "${mass[$i]}" ]]; then
		mass[$i]=0
	else
		echo "Only numbers"
		exit 1
	fi
done

echo "Wait a minute..."
custom_date="$(date --date="-${mass[0]} day -${mass[1]} hour -${mass[2]} minutes " '+%Y-%m-%dT%H:%M:%S')"
echo "$custom_date"
#aws ec2 describe-snapshots | jq '[.Snapshots[] | select(.StartTime >= "'$custom_date'") | {Description: .Description, StartTime: .StartTime, SnapshotId: .SnapshotId, VolumeSize: .VolumeSize}] | sort_by(.StartTime) | reverse'
aws ec2 describe-snapshots --query "Snapshots[?(StartTime>='$custom_date')].{Description:Description, StartTime:StartTime, SnapshotId:SnapshotId, VolumeSize:VolumeSize}" | jq 'sort_by(.StartTime) | reverse'